package:
  name: pcg-cpp
  version: 20170823

source:
  git_url: https://github.com/imneme/pcg-cpp.git
  git_rev: 0ca2e8ea6ba212bdfbc6219c2313c45917e34b8d

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
